#!/bin/bash

function check_for_bin {
    which $1 >/dev/null 2>&1; echo -n $?;
}

function not_found {
    echo "unable to find a binary for '$1'"
}

echo -n 'PHP:              '
if [[ $(check_for_bin php) -gt 0 ]]; then
    not_found php
else
    php -r "echo phpversion().PHP_EOL;"
fi

echo -n "Nginx:            "
if [[ $(check_for_bin nginx) -gt 0 ]]; then
    not_found nginx
else
    nginx -v
fi

echo -n "Redis:            "
if [[ $(check_for_bin redis-server) -gt 0 ]]; then
    not_found redis-server
    echo "not found"
else
    redis-server --version
fi

echo -n "Varnish:          "
if [[ $(check_for_bin varnishd) -gt 0 ]]; then
    not_found varnishd
else
    varnishd -V 2>&1 | head -n1
fi

echo -n "Mysql:            "
if [[ $(check_for_bin mysqld) -gt 0 ]]; then
    not_found mysqld
else
    mysqld --version
fi

echo -n "Elasticsearch:    "
if [[ $(check_for_bin elasticsearch) -gt 0 ]]; then
    not_found elasticsearch
else
    elasticsearch --version
fi
